apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::833866812283:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-TZ0LERK8CVDX
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::833866812283:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-28T02:48:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1736"
  uid: 2ad1341e-4cf8-4f13-88e7-5e3609c593bc
